// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8YIVC-id9ynrVr81R9YVP0bLMtIpSWY',
    appId: '1:394603046921:web:3ed1c7b99538c21932f0d8',
    messagingSenderId: '394603046921',
    projectId: 'fir-flutter-auth-cf74a',
    authDomain: 'fir-flutter-auth-cf74a.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-cf74a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMgedQozfINsSBvb5HHOTxUh3XWP6wNbo',
    appId: '1:394603046921:android:d443e9ed6c97fb6432f0d8',
    messagingSenderId: '394603046921',
    projectId: 'fir-flutter-auth-cf74a',
    storageBucket: 'fir-flutter-auth-cf74a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGd0voq6ZWwO2lp1YWPe_ApcS9SSHDoGY',
    appId: '1:394603046921:ios:6c859b170d5db65132f0d8',
    messagingSenderId: '394603046921',
    projectId: 'fir-flutter-auth-cf74a',
    storageBucket: 'fir-flutter-auth-cf74a.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGd0voq6ZWwO2lp1YWPe_ApcS9SSHDoGY',
    appId: '1:394603046921:ios:3cc8adcdc4a0a55132f0d8',
    messagingSenderId: '394603046921',
    projectId: 'fir-flutter-auth-cf74a',
    storageBucket: 'fir-flutter-auth-cf74a.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuthentication.RunnerTests',
  );
}
